version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21

  build:
    commands:
      - echo "Building application..."
      - chmod +x mvnw
      - ./mvnw clean package

artifacts:
  files:
    - target/*.jar

cache:
  paths:
    - /root/.m2/**/*
